#!/usr/bin/env node

import { createHash } from 'node:crypto'
import { mkdirSync, writeFileSync, readFileSync, rmSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const OUT = join(ROOT, 'public', 'fonts')

const SPEC =
  'family=Unbounded:wght@400;600;700' +
  '&family=DM+Sans:ital,opsz,wght@0,9..40,300;0,9..40,400;0,9..40,500;1,9..40,400' +
  '&family=DM+Mono:wght@400;500'
const SUBSETS = new Set(['latin', 'latin-ext'])

const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'

const OFL = 'https://raw.githubusercontent.com/google/fonts/main/ofl/unbounded/OFL.txt'

const res = await fetch(`https://fonts.googleapis.com/css2?${SPEC}&display=swap`, {
  headers: { 'User-Agent': UA },
})
if (!res.ok) throw new Error(`Google Fonts responded ${res.status}`)
const css = await res.text()

rmSync(OUT, { recursive: true, force: true })
mkdirSync(OUT, { recursive: true })

const blocks = [...css.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g)]
if (!blocks.length) throw new Error('no @font-face blocks parsed')

const slug = s => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')

const groups = new Map()

for (const [, subset, block] of blocks) {
  if (!SUBSETS.has(subset)) continue

  const family = block.match(/font-family:\s*'([^']+)'/)?.[1]
  const weights = (block.match(/font-weight:\s*([\d\s]+);/)?.[1] ?? '400')
    .trim()
    .split(/\s+/)
    .map(Number)
  const style = block.match(/font-style:\s*(\w+)/)?.[1] ?? 'normal'
  const url = block.match(/url\((https:[^)]+\.woff2)\)/)?.[1]
  const range = block.match(/unicode-range:\s*([^;]+);/)?.[1]
  if (!family || !url) continue

  const file = await fetch(url, { headers: { 'User-Agent': UA } })
  if (!file.ok) throw new Error(`${family} ${weights} ${subset}: ${file.status}`)
  const bytes = Buffer.from(await file.arrayBuffer())
  const hash = createHash('sha256').update(bytes).digest('hex').slice(0, 8)

  const existing = groups.get(hash)
  if (existing) {
    existing.weights.push(...weights)
    continue
  }
  groups.set(hash, { family, style, subset, range, bytes, weights: [...weights] })
}

const PRELOAD = ['Unbounded', 'DM Sans']

const out = []
const preload = []
for (const g of groups.values()) {
  const lo = Math.min(...g.weights)
  const hi = Math.max(...g.weights)
  const span = lo === hi ? `${lo}` : `${lo} ${hi}`
  const name = `${slug(g.family)}-${span.replace(' ', '-')}${g.style === 'italic' ? '-italic' : ''}-${g.subset}.woff2`

  if (PRELOAD.includes(g.family) && g.subset === 'latin' && g.style === 'normal') {
    preload.push(name)
  }

  writeFileSync(join(OUT, name), g.bytes)
  out.push(
    `@font-face {\n` +
      `  font-family: '${g.family}';\n` +
      `  font-style: ${g.style};\n` +
      `  font-weight: ${span};\n` +
      `  font-display: swap;\n` +
      `  src: url('/fonts/${name}') format('woff2');\n` +
      (g.range ? `  unicode-range: ${g.range};\n` : '') +
      `}`,
  )
  console.log(`  ${name}  ${(g.bytes.length / 1024).toFixed(1)} kB`)
}
const kept = groups.size

writeFileSync(
  join(ROOT, 'src', 'styles', 'fonts.css'),
  `/* Generated by scripts/fetch-fonts.mjs */\n\n` +
    out.join('\n\n') +
    '\n',
)

const indexPath = join(ROOT, 'index.html')
const index = readFileSync(indexPath, 'utf8')
const tags = preload
  .map(
    n =>
      `    <link\n` +
      `      rel="preload"\n` +
      `      href="/fonts/${n}"\n` +
      `      as="font"\n` +
      `      type="font/woff2"\n` +
      `      crossorigin\n` +
      `    />`,
  )
  .join('\n')

const block = /[ \t]*<link\r?\n?[^>]*rel="preload"[^>]*as="font"[^>]*\/>(\s*<link\r?\n?[^>]*rel="preload"[^>]*as="font"[^>]*\/>)*/
if (!block.test(index)) throw new Error('no font preload block found in index.html')
writeFileSync(indexPath, index.replace(block, tags))

const ofl = await fetch(OFL)
if (!ofl.ok) throw new Error(`OFL.txt: ${ofl.status}`)
writeFileSync(join(OUT, 'OFL.txt'), await ofl.text())

console.log(`✓ ${kept} woff2 files + OFL.txt → public/fonts/, src/styles/fonts.css rewritten`)
