#!/usr/bin/env node

import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import opentype from 'opentype.js'

const HERE = dirname(fileURLToPath(import.meta.url))
const CACHE = join(HERE, '.fonts')

const FONTS = {
  unbounded:
    'https://fonts.gstatic.com/s/unbounded/v12/Yq6F-LOTXCb04q32xlpat-6uR42XTqtG6__2040.ttf',
  dmmono: 'https://fonts.gstatic.com/s/dmmono/v16/aFTU7PB1QTsUX8KYhh0.ttf',
}

async function font(name) {
  const path = join(CACHE, `${name}.ttf`)
  try {
    return opentype.parse(readFileSync(path).buffer)
  } catch {
    const res = await fetch(FONTS[name])
    if (!res.ok) throw new Error(`${name}: ${res.status}`)
    const buf = Buffer.from(await res.arrayBuffer())
    writeFileSync(path, buf)
    return opentype.parse(buf.buffer)
  }
}

function outline(f, text, size, tracking) {
  const scale = size / f.unitsPerEm
  const glyphs = []
  let x = 0
  let capTop = 0
  for (const ch of text) {
    const g = f.charToGlyph(ch)
    const p = g.getPath(0, 0, size)
    const d = p.toPathData(3)
    if (d.includes('NaN')) throw new Error(`NaN in glyph "${ch}"`)
    capTop = Math.min(capTop, p.getBoundingBox().y1)
    glyphs.push({ d, x: Number(x.toFixed(3)) })
    x += g.advanceWidth * scale + tracking
  }
  return {
    glyphs,
    advance: Number((x - tracking).toFixed(3)),
    capHeight: Number((-capTop).toFixed(2)),
  }
}

const SIZE = 100
const wordmark = outline(await font('unbounded'), 'SPIRALES', SIZE, SIZE * 0.16)
const domain = outline(await font('dmmono'), 'spirales.tech', SIZE, SIZE * 0.18)

const fmt = o =>
  `{\n  advance: ${o.advance},\n  capHeight: ${o.capHeight},\n  glyphs: [\n` +
  o.glyphs.map(g => `    { x: ${g.x}, d: '${g.d}' },`).join('\n') +
  `\n  ],\n}`

writeFileSync(
  join(HERE, 'brand-glyphs.mjs'),
  `// Generated by scripts/regenerate-glyphs.mjs

export const WORDMARK = ${fmt(wordmark)}

export const DOMAIN = ${fmt(domain)}
`,
)

console.log(`✓ ${wordmark.glyphs.length} + ${domain.glyphs.length} glyphs → scripts/brand-glyphs.mjs`)
